<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/1_Basics/20_Library.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Libraries

## Overview

### Notes
* A library is a collection of packages or modules that are grouped together to extend functionality
* Types:
  1. Standard libraries (included with Python)
  2. Third-party libraries & packages (need to be installed)
* Typically, installed using package managers like pip or conda

### What the heck are Packages then?
- A package can include modules and sub-packages 

### Packages vs Libraries
- Python uses packages to organize inside it's libraries, and libraries to provide and extend functionalities.   
- While **all libraries can be considered packages** (if they are structured that way), **not all packages are libraries**.

### Importance 
* It helps save time, standardize processes, and add complex functionalities easily.
* Used for things like data analysis, machine learning, web development, automation, and more.

## Standard Python Libraries

### Notes

* The same as modules, we use the `from` and `import` keywords. 
    * The`import` gets the module modules
    * The `from` is to get specific attributes from a module directly
* When to use one or the other: 
    * `import module_name`: When you need to access several functions or attributes from a module
    * `from module_name import attribute_name`: Use when you only need a specific function or attribute from a module

### Importance of Libraries

### Notes

What if we want to be able to manipulate files? We can use the standard library in Python to open, read, write, and close files.

Functions:
- `open`: Opens a file. The 'r' mode is for reading, 'w' for writing (overwrites content), 'a' for appending, and 'b' for binary mode.
- `read`: Reads the content of an opened file. Can also use `readline()` for a single line or `readlines()` for all lines as a list.
- `write`: Writes a string to an opened file. If the file is opened in append mode ('a'), the text is added at the end.
- `close`: Closes an opened file, which is important for freeing up system resources.

### Examples

**Note: This example is meant to be done on Google Colab with accesses to the `sample_data` folder**.

To read the contents of `california_housing_test.csv` and print them:

In [1]:
# Open the file in read mode
file = open('sample_data/california_housing_test.csv')

# Read the file
content = file.read()

# Close the file
file.close()

# Print the content
print(content)

FileNotFoundError: [Errno 2] No such file or directory: 'sample_data/california_housing_test.csv'

Now, what if we want to get this data into something usable (like a dictionary) to actually start performing data analysis:

In [ ]:
import csv

data_dict = {}
for index, row in enumerate(csv.reader(content.strip().split('\n'))):
    if index == 0:
        # Initialize dictionary with column headers as keys
        for column in row:
            data_dict[column] = []
    else:
        # Append each element in the row to the correct list in the dictionary
        for col_index, value in enumerate(row):
            data_dict[list(data_dict.keys())[col_index]].append(value)

# Print the dictionary to verify contents
print(data_dict)

Okay, that's honestly a lot to do each time you want to work with CSV files. But we could use a third-party library called `pandas` instead to load in files a lot easier.

## Third-Party Libraries

### Example w/ Pandas

With a library like `pandas`, you can read the file and convert it in 3 lines of code!

In [2]:
import pandas as pd

# Create a dataframe from csv file
df = pd.read_csv('sample_data/california_housing_test.csv')

# Print the dataframe
df

# get sume of total_bedrooms
sum_total_bedrooms = df['total_bedrooms'].sum()

FileNotFoundError: [Errno 2] No such file or directory: 'sample_data/california_housing_test.csv'

In [9]:
import pandas as pd
datacollection=pd.read_csv("C:\\Users\\RAMTIN\\Documents\\GitHub\\Python_Data_Analytics_Course_Luke Barousse\\data_jobs.csv")

In [ ]:
import pandas as pd
datacollection=pd.read_csv()

In [11]:
import os
print(os.getcwd())

c:\Users\RAMTIN\Documents\GitHub\Python_Data_Analytics_Course_Luke Barousse\1_Basics

In [12]:

dc=pd.read_csv("../data_jobs.csv")

In [14]:
dc['company_name']

0                       Boehringer Ingelheim
1                 Hewlett Packard Enterprise
2                   ALPHA Augmented Services
3               Southwest Research Institute
4                            Kristina Daniel
                         ...
785736    CAREERSTAR INTERNATIONAL PTE. LTD.
785737                      HABA FAMILYGROUP
785738                 Lendlease Corporation
785739                           Capital One
785740                                Trigyn
Name: company_name, Length: 785741, dtype: str

In [13]:
dc

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [10]:
datacollection

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

### Notes

* These are third party packages and libraries (not included in Python Standard Library) that need to be installed separately.
* The way you install a package depends on the package manager you are using
* There are two main ways to do this:
    1. *Pip* - If you use `pip` for package management (Google Colab uses this).
    2. *Conda* - If you use `conda` or `mamba` for package management (We'll use this in the Advanced Chapter).

**NOTE: We'll go more into package management in the advanced chapter.**

### Common Third Party Libraries

Below are some common third party libraries used in data science:
- **Pandas**: Offers data structures and operations for manipulating numerical tables and time series.
- **NumPy**: Supports large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions.
- **Matplotlib**: A plotting library for creating static, animated, and interactive visualizations in Python.
- **Seaborn**: Provides a high-level interface for drawing attractive and informative statistical graphics.
- **SciPy**: Used for scientific and technical computing, offering modules for optimization, linear algebra, and more.
- **Scikit-learn**: Implements a range of machine learning algorithms for data mining, data analysis, and machine learning tasks.
- **Plotly**: Creates interactive and visually appealing graphs for web publication.

### Where do I find packages?

[PyPi](https://pypi.org/) - for `pip`  
[Anaconda](https://www.anaconda.com/) - for `conda`

### Listing Packages Installed

If you're running this in Google Collab, use the following:

In [4]:
!pip list

Package             Version
------------------- --------
aiohttp             3.9.5
aiosignal           1.3.1
appnope             0.1.4
asttokens           2.4.1
async-timeout       4.0.3
attrs               23.2.0
backcall            0.2.0
Brotli              1.1.0
certifi             2024.2.2
charset-normalizer  3.3.2
colorama            0.4.6
comm                0.2.2
contourpy           1.2.1
cycler              0.12.1
datasets            2.19.0
debugpy             1.8.1
decorator           5.1.1
dill                0.3.8
executing           2.0.1
filelock            3.14.0
fonttools           4.51.0
frozenlist          1.4.1
fsspec              2024.3.1
huggingface_hub     0.22.2
idna                3.7
importlib_metadata  7.1.0
importlib_resources 6.4.0
ipykernel           6.29.3
ipython             8.12.0
jedi                0.19.1
jupyter_client      8.6.1
jupyter_core        4.12.0
kiwisolver          1.4.5
matplotlib          3.8.4
matplotlib-inline   0.1.6
multidict           6.0.5
multiprocess        0.70.16
munkres             1.1.4
nest_asyncio        1.6.0
numpy               1.26.4
packaging           24.0
pandas              2.2.2
parso               0.8.4
pexpect             4.9.0
pickleshare         0.7.5
pillow              10.3.0
pip                 24.0
prompt-toolkit      3.0.42
psutil              5.9.8
ptyprocess          0.7.0
pure-eval           0.2.2
pyarrow             15.0.2
pyarrow-hotfix      0.6
Pygments            2.17.2
pyparsing           3.1.2
PySocks             1.7.1
python-dateutil     2.9.0
pytz                2024.1
PyYAML              6.0.1
pyzmq               25.1.2
requests            2.31.0
seaborn             0.13.2
setuptools          69.2.0
six                 1.16.0
stack-data          0.6.2
tornado             6.4
tqdm                4.66.2
traitlets           5.14.2
typing_extensions   4.11.0
tzdata              2024.1
unicodedata2        15.1.0
urllib3             2.2.1
wcwidth             0.2.13
wheel               0.43.0
xxhash              3.4.1
yarl                1.9.4
zipp                3.17.0

If you're running this locally using Conda run this:

In [5]:
!conda list

# packages in environment at /Users/lukebarousse/opt/anaconda3/envs/python_course:
#
# Name                    Version                   Build  Channel
aiohttp                   3.9.5            py39ha09f3b3_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.18               hb47d15a_0    conda-forge
aws-c-cal                 0.6.11               hbce485b_0    conda-forge
aws-c-common              0.9.15               h10d778d_0    conda-forge
aws-c-compression         0.2.18               h53e3db5_3    conda-forge
aws-c-event-stream        0.4.2                he461af8_8    conda-forge
aws-c-http                0.8.1               h0afc28a_10    conda-forge
aws-c-io                  0.14.7               h6254544_6    conda-forge
aws-c-mqtt                0.10.4               hd66502f_0    conda-forge
aws-c-s3                  0.5.7                h5d4520e_2    conda-forge
aws-c-sdkutils            0.1.15               h53e3db5_3    conda-forge
aws-checksums             0.1.18               h53e3db5_3    conda-forge
aws-crt-cpp               0.26.8               ha933895_2    conda-forge
aws-sdk-cpp               1.11.267             h8dd24e3_7    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
brotli-python             1.1.0            py39h840bb9f_1    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.28.1               h10d778d_0    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1            py39h0ca7971_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
datasets                  2.19.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.1            py39hd253f6c_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.8              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
filelock                  3.14.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.51.0           py39ha09f3b3_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
frozenlist                1.4.1            py39ha09f3b3_0    conda-forge
fsspec                    2024.3.1           pyhca7485f_0    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
glog                      0.7.0                h31b1b29_0    conda-forge
huggingface_hub           0.22.2             pyhd8ed1ab_0    conda-forge
icu                       73.2                 hf5e326d_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.3             pyh3cd1d5f_0    conda-forge
ipython                   8.12.0             pyhd1c38e8_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.12.0           py39h6e9494a_0    conda-forge
kiwisolver                1.4.5            py39h8ee36c8_1    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
lcms2                     2.16                 ha2f27b4_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libabseil                 20240116.2      cxx17_hc1bcbd7_0    conda-forge
libarrow                  15.0.2           hfba3c4c_6_cpu    conda-forge
libarrow-acero            15.0.2           ha0df490_6_cpu    conda-forge
libarrow-dataset          15.0.2           ha0df490_6_cpu    conda-forge
libarrow-flight           15.0.2           h41520de_6_cpu    conda-forge
libarrow-flight-sql       15.0.2           hb2e0ddf_6_cpu    conda-forge
libarrow-gandiva          15.0.2           h81ca85a_6_cpu    conda-forge
libarrow-substrait        15.0.2           hb2e0ddf_6_cpu    conda-forge
libblas                   3.9.0           22_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           22_osx64_openblas    conda-forge
libcrc32c                 1.1.2                he49afe7_0    conda-forge
libcurl                   8.7.1                h726d00d_0    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.20                 h49d49c5_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 h10d778d_2    conda-forge
libevent                  2.1.12               ha90c15b_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libgoogle-cloud           2.23.0               h651e89d_1    conda-forge
libgoogle-cloud-storage   2.23.0               ha67e85c_1    conda-forge
libgrpc                   1.62.2               h384b2fc_0    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libjpeg-turbo             3.0.0                h0dc2134_1    conda-forge
liblapack                 3.9.0           22_osx64_openblas    conda-forge
libllvm16                 16.0.6               hbedff68_3    conda-forge
libnghttp2                1.58.0               h64cf6d3_1    conda-forge
libopenblas               0.3.27          openmp_hfef2a42_0    conda-forge
libparquet                15.0.2           h7cd3cfe_6_cpu    conda-forge
libpng                    1.6.43               h92b6c6a_0    conda-forge
libprotobuf               4.25.3               h4e4d658_0    conda-forge
libre2-11                 2023.09.01           h81f5012_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.45.2               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libthrift                 0.19.0               h064b379_1    conda-forge
libtiff                   4.6.0                h129831d_3    conda-forge
libutf8proc               2.8.0                hb7f2c08_0    conda-forge
libwebp-base              1.3.2                h10d778d_1    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libxml2                   2.12.6               hc0ae0f7_2    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               18.1.3               hb6ac08f_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
matplotlib                3.8.4            py39h6e9494a_0    conda-forge
matplotlib-base           3.8.4            py39h7070ae8_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
multidict                 6.0.5            py39ha30fb19_0    conda-forge
multiprocess              0.70.16          py39ha09f3b3_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4.20240210         h73e2aa4_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
numpy                     1.26.4           py39h28c39a1_0    conda-forge
openjpeg                  2.5.2                h7310d3a_0    conda-forge
openssl                   3.3.0                hd75f5a5_0    conda-forge
orc                       2.0.0                hf146577_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2            py39haf03413_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.3.0           py39h9dabb2a_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
prompt_toolkit            3.0.42               hd8ed1ab_0    conda-forge
psutil                    5.9.8            py39ha09f3b3_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   15.0.2          py39h52bf62a_6_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.19          h7a9c478_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python-xxhash             3.4.1            py39hdc70f33_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1            py39hdc70f33_1    conda-forge
pyzmq                     25.1.2           py39hcb7a90d_0    conda-forge
re2                       2023.09.01           hb168e87_2    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
seaborn                   0.13.2                   pypi_0    pypi
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                h6dc393e_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
tornado                   6.4              py39ha09f3b3_0    conda-forge
tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.2             pyhd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unicodedata2              15.1.0           py39hdc70f33_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xxhash                    0.8.2                h4140336_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
yarl                      1.9.4            py39ha09f3b3_0    conda-forge
zeromq                    4.3.5                h93d8f39_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                h829000d_0    conda-forge

Note: `!pip list` will work if running conda; BUT it won't include all your packages.

### Installing Packages

#### Notes

- Once again dependent on your package manager will depend on whether you need to pip or conda install.

#### Examples

##### `pip` Install (Google Colab example)

Google Colab comes standard with a bunch of libraries installed; but here's one we don't have:

In [ ]:
!pip install pyjokes

##### `conda` install (Local Example) 

**Note: This is an example ONLY if you are running locally and have Anaconda installed (on Colab, pandas is already installed)**.

Since `pandas` is a library outside of Python's standard library; so we can install with conda.

In [ ]:
!conda install pandas

## Import the Package

Now that we've installed a library we need to import it. This lets us use it in our specific notebook / environment (we'll get more into environments later in the advanced section).

We will be showing how to import Python libraries, packages and modules. Here's a reminder of the difference between all 3:
1. **Library**: A collection of packages and modules.
2. **Package**: A directory with Python scripts and an `__init__.py` file.
3. **Module**: A Python script file that can be imported.

### Examples

In [ ]:
import pyjokes

pyjokes.get_joke()