<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/1_Basics/25_Pandas_Cleaning.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Pandas Cleaning

Load in the data.

In [1]:
# Install datasets Library (if not already installed)
# !pip install -U datasets

# Importing Libraries
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

/Users/lukebarousse/opt/anaconda3/envs/python_course/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [1]:
import pandas as pd
df=pd.read_csv('../data_jobs.csv')
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [9]:
df.loc[:,"job_posted_date"].dt.day_name()

0           Friday
1         Saturday
2          Tuesday
3          Tuesday
4           Monday
            ...
785736      Monday
785737      Sunday
785738      Sunday
785739      Sunday
785740      Monday
Name: job_posted_date, Length: 785741, dtype: str

In [2]:
# pd.to_datetime(df.loc[:,'job_posted_date'])
# df.loc[:,'job_posted_date']=pd.to_datetime(df.loc[:,'job_posted_date'])
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

type(df.loc[6,'job_posted_date'])

pandas.Timestamp

In [ ]:
df['job_posted_date_month']=df.loc[:,"job_posted_date"].dt.month()

In [22]:
df['job_posted_date_month']=df.loc[:,"job_posted_date"].dt.month

In [35]:
print(type(df.loc[2,'job_posted_date_month']))
print(type(df.loc[5,'job_posted_date']))
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])
print(type(df.loc[5,'job_posted_date']))

<class 'numpy.int32'>
<class 'pandas.Timestamp'>
<class 'pandas.Timestamp'>

In [ ]:
df['job_posted_date_month']=df.loc[:,"job_posted_date"].dt.month

In [ ]:
df.sort_values(by=['job_posted_date'],ascending=True)
df.Dro

In [ ]:
df.to_csv('data_jobs_updated.csv', index=False

In [96]:
a=df.copy()

In [105]:
b.info()

<class 'pandas.DataFrame'>
Index: 785735 entries, 96906 to 112373
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785735 non-null  str
 1   job_title              785734 non-null  str
 2   job_location           784690 non-null  str
 3   job_via                785727 non-null  str
 4   job_schedule_type      773068 non-null  str
 5   job_work_from_home     785735 non-null  bool
 6   search_location        785735 non-null  str
 7   job_posted_date        785735 non-null  datetime64[us]
 8   job_no_degree_mention  785735 non-null  bool
 9   job_health_insurance   785735 non-null  bool
 10  job_country            785686 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785717 non-null  str
 14  job_skills             668699 non-null  str
 15  job_type_skills        668699 non-null  str
 16  job_posted_date_month  785735 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(1), int32(1), str(11)
memory usage: 89.2 MB

In [107]:
b.info()

<class 'pandas.DataFrame'>
Index: 785735 entries, 96906 to 112373
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785735 non-null  str
 1   job_title              785734 non-null  str
 2   job_location           784690 non-null  str
 3   job_via                785727 non-null  str
 4   job_schedule_type      773068 non-null  str
 5   job_work_from_home     785735 non-null  bool
 6   search_location        785735 non-null  str
 7   job_posted_date        785735 non-null  datetime64[us]
 8   job_no_degree_mention  785735 non-null  bool
 9   job_health_insurance   785735 non-null  bool
 10  job_country            785686 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785717 non-null  str
 14  job_skills             668699 non-null  str
 15  job_type_skills        668699 non-null  str
 16  job_posted_date_month  785735 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(1), int32(1), str(11)
memory usage: 89.2 MB

In [113]:
# a.drop(index=[2], inplace=True)
a.drop(index=[104526], inplace=True)
a

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_date_month
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
73376,Data Analyst,Data Analyst,"Sunnyvale, CA",via CareerBuilder,Full-time,False,"California, United States",2023-01-01 00:00:38,False,False,United States,NaN,NaN,"ICONMA, LLC","['sql', 'python']","{'programming': ['sql', 'python']}",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12

In [108]:
b

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_date_month
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
73376,Data Analyst,Data Analyst,"Sunnyvale, CA",via CareerBuilder,Full-time,False,"California, United States",2023-01-01 00:00:38,False,False,United States,NaN,NaN,"ICONMA, LLC","['sql', 'python']","{'programming': ['sql', 'python']}",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12

In [94]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_date_month
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
104526,Data Analyst,Jr. Data Analyst,"Torrance, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:00:38,False,False,United States,NaN,NaN,Aquent,['excel'],{'analyst_tools': ['excel']},1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12

In [25]:
df["job_posted_date"].dt.day_name()

0           Friday
1         Saturday
2          Tuesday
3          Tuesday
4           Monday
            ...
785736      Monday
785737      Sunday
785738      Sunday
785739      Sunday
785740      Monday
Name: job_posted_date, Length: 785741, dtype: str

In [41]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_date_month
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN,6
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",10
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",7
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete...",3
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi...",3
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",3
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",3
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}",3

In [6]:
type(df.loc[0,'job_posted_date'])

str

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 86.2 MB

## Date and Time

### Datetime

#### Notes

* `pd.to_datetime()`: Convert argument to datetime.

#### Example

In our DataFrame the `job_posted_date` is actually a string not a datetime format. First let's convert it to datetime format. 

We'll also use `info()` to check if the data type changed from a string to a `datetime` format.

In [2]:
# Convert 'job_posted_date' to datetime without specifying the exact format
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 787686 entries, 0 to 787685
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        787686 non-null  object
 1   job_title              787685 non-null  object
 2   job_location           786646 non-null  object
 3   job_via                787679 non-null  object
 4   job_schedule_type      774976 non-null  object
 5   job_work_from_home     787686 non-null  bool
 6   search_location        787686 non-null  object
 7   job_posted_date        787686 non-null  datetime64[ns]
 8   job_no_degree_mention  787686 non-null  bool
 9   job_health_insurance   787686 non-null  bool
 10  job_country            787633 non-null  object
 11  salary_rate            33073 non-null   object
 12  salary_year_avg        22026 non-null   float64
 13  salary_hour_avg        10649 non-null   float64
 14  company_name           787668 non-null  object
 15  job_skills             670364 non-null  object
 16  job_type_skills        670364 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.4+ MB

### Date

#### Notes

* `dt`: accessor that provides a way to access specialized methods and properties we use to work with datatime data within a pandas series. 
* `date`: extract the date component from the datetime object in the series. 
* Use together `dt.date` on our series.

#### Example

Now let's turn it from a datetime to a date using `dt.date`.

In [3]:
df['job_posted_date'] = df['job_posted_date'].dt.date

df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Data Analyst,Data Analytics,"Monterrey, Nuevo Leon, Mexico",via BeBee,Part-time,False,Mexico,2023-12-05,False,False,Mexico,None,NaN,NaN,2U Bootcamps Instructional Engagement,"['go', 'python', 'mongodb', 'mongodb', 'css', ...","{'analyst_tools': ['tableau'], 'databases': ['..."
1,Data Scientist,Data Scientist Intern,"Lisbon, Portugal",via Empregos Trabajo.org,Full-time,False,Portugal,2023-08-20,False,False,Portugal,None,NaN,NaN,Nokia,"['sql', 'python', 'sql server', 'oracle', 'azu...","{'analyst_tools': ['sap'], 'cloud': ['oracle',..."
2,Data Analyst,"Manager, Data Analytics","Guanacaste Province, Lagunilla, Costa Rica",via BeBee Costa Rica,Full-time,False,Costa Rica,2023-11-21,False,False,Costa Rica,None,NaN,NaN,Thermo Fisher Scientific,None,None
3,Data Engineer,Data Engineer,"Lambayeque, Peru",via BeBee Perú,Full-time,False,Peru,2023-11-21,True,False,Peru,None,NaN,NaN,Emprego,None,None
4,Data Analyst,Technical Data Analyst,"Fairfax, VA",via Indeed,Contractor,False,"New York, United States",2023-12-20,True,False,United States,None,NaN,NaN,Info Origin Inc.,"['sql', 'python', 'jira']","{'async': ['jira'], 'programming': ['sql', 'py..."

#### Note: For the rest of the time we're loading the data in we'll be automatically turn the `job_posted_date` column into a datetime object.

## Sorting Values

### Notes

* `sort_values()` sorts a DataFrame or a specific column in ascending or descending order based on one or more columns. 
* Typically this is used to sort by a specific column/s.
* Parameters: 
    * `by` - column name or list of column names to sort by
    * `ascending` - boolean or list of booleans, default `True`, to sort by descending you would use `False`
    * `inplace` - whether to modify the DataFrame in place or return a new one

### Example

Let's sort our DataFrame by the `job_posted_date` in descending order (from most recent date to least).

In [4]:
df.sort_values(by='job_posted_date', ascending=False, inplace=True)
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
287190,Data Engineer,Data Engineer H/F H/F,France,via BeBee,Full-time,False,France,2023-12-31,False,False,France,None,NaN,NaN,Bolloré Group,"['python', 'azure', 'aws', 'gcp', 'databricks'...","{'analyst_tools': ['tableau', 'cognos', 'power..."
770443,Data Scientist,Data Scientist,"Chaville, France",via BeBee,Full-time,False,France,2023-12-31,False,False,France,None,NaN,NaN,DASSAULT SYSTEMES,"['python', 'sql', 'power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
770111,Data Scientist,(Junior) Analyst - Website/Social Media*,"Frankfurt, Germany",via XING,Full-time,False,Germany,2023-12-31,True,False,Germany,None,NaN,NaN,Nintendo of Europe GmbH,"['sql', 'html', 'css', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr..."
465217,Data Engineer,Work From Home Data Platform Engineer,"Risaralda, Caldas, Colombia",via Sercanto,Full-time,False,Colombia,2023-12-31,True,False,Colombia,None,NaN,NaN,Bairesdev S.a.,"['python', 'scala', 'java', 'nosql', 'kafka', ...","{'libraries': ['kafka', 'airflow'], 'programmi..."
449221,Data Analyst,وظائف Data Analyst (Part time) – الجيزة,"Giza, El Omraniya, Egypt",via وظائف,Part-time,False,Egypt,2023-12-31,True,False,Egypt,None,NaN,NaN,شركة,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704528,Data Scientist,Data Scientist 2,"Atlanta, GA",via Trabajo.org,Full-time,False,"Florida, United States",2022-12-31,False,True,United States,None,NaN,NaN,UnitedHealth Group,"['python', 'sql', 'hugging face', 'pytorch', '...","{'analyst_tools': ['excel'], 'libraries': ['hu..."
671315,Data Scientist,Data Quality Assessment,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,2022-12-31,False,False,Kenya,None,NaN,NaN,SoCha,None,None
621134,Data Analyst,Data Analyst,"West Chicago, IL",via LinkedIn,Full-time,False,"Illinois, United States",2022-12-31,False,False,United States,None,NaN,NaN,Epsilon,"['sas', 'sas', 'sql', 'r', 'python', 'hadoop',...","{'analyst_tools': ['sas', 'word', 'excel', 'po..."
421621,Data Scientist,Big Data Systems Engineer II | Cape Town,"Cape Town, South Africa",via Trabajo.org,Full-time,False,South Africa,2022-12-31,True,False,South Africa,None,NaN,NaN,Progressive Edge,"['azure', 'linux', 'terraform']","{'cloud': ['azure'], 'os': ['linux'], 'other':..."
481817,Data Scientist,"Associate Data Scientist, Graduates of Summer ...","Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2022-12-31,False,False,Denmark,None,NaN,NaN,IBM Client Innovation Center,"['java', 'python', 'r', 'c#']","{'programming': ['java', 'python', 'r', 'c#']}"

## Adding a Column

### Notes

- If you want to create a column you'll need to use the `df['column_name']` syntax.

### Example

Here we are creating a new column called 'Is Data Analyst' and saying if the column `job_title_short` is equal to 'Data Analyst' then then return 1 if not, return 0. It does this by using `astype(int)`.

In [5]:
df['Is Data Analyst'] = (df.job_title_short == 'Data Analyst').astype(int)

Let's view this new column we created.

In [6]:
df['Is Data Analyst']

287190    0
770443    0
770111    0
465217    0
449221    1
         ..
704528    0
671315    0
621134    1
421621    0
481817    0
Name: Is Data Analyst, Length: 787686, dtype: int64

Did this work? Let's look at cases when this column is greater than 0, which means it is equal to 1 (aka it's true). We can use our row filtering we learned in the last section.

In [7]:
df[df['Is Data Analyst'] > 0]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,Is Data Analyst
449221,Data Analyst,وظائف Data Analyst (Part time) – الجيزة,"Giza, El Omraniya, Egypt",via وظائف,Part-time,False,Egypt,2023-12-31,True,False,Egypt,None,NaN,NaN,شركة,None,None,1
443614,Data Analyst,Engineer ii data analyst hybrid,"Aguadilla, Puerto Rico",via Sercanto,Full-time,False,Puerto Rico,2023-12-31,True,False,Puerto Rico,None,NaN,NaN,Jobzem (2497612),None,None,1
605365,Data Analyst,Data Analyst at United Nations Environment Pro...,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,2023-12-31,False,False,Kenya,None,NaN,NaN,United Nations Environment Programme (UNEP),"['sql', 'python', 'qlik', 'tableau', 'git']","{'analyst_tools': ['qlik', 'tableau'], 'other'...",1
776838,Data Analyst,Data Analyst,Ras Al-Khaimah - Ras al Khaimah - United Arab ...,via BeBee,Full-time,False,United Arab Emirates,2023-12-31,False,False,United Arab Emirates,None,NaN,NaN,Work corp,"['sql', 'python', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr...",1
776816,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,NaN,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512850,Data Analyst,Junior Data Analyst,Australia,via Laimoon.com,Contractor,False,Australia,2022-12-31,True,False,Australia,None,NaN,NaN,4C Strategies,"['go', 'qlik']","{'analyst_tools': ['qlik'], 'programming': ['g...",1
690197,Data Analyst,Insurance Data Analyst,Hong Kong,via BeBee 香港,Full-time,False,Hong Kong,2022-12-31,False,False,Hong Kong,None,NaN,NaN,10Life Group Limited,"['python', 'sql', 'vba', 'excel', 'power bi', ...","{'analyst_tools': ['excel', 'power bi', 'table...",1
604299,Data Analyst,Data Analyst / Data Steward - Real Estate (m/w...,"Cologne, Germany",via My ArkLaMiss Jobs,Full-time,False,Germany,2022-12-31,True,False,Germany,None,NaN,NaN,BNP Paribas Real Estate,None,None,1
588085,Data Analyst,Data Analyst,"Dublin, Ireland",via BeBee Ireland,Full-time,False,Ireland,2022-12-31,True,False,Ireland,None,NaN,NaN,Allied Irish Bank,['gdpr'],{'libraries': ['gdpr']},1
621134,Data Analyst,Data Analyst,"West Chicago, IL",via LinkedIn,Full-time,False,"Illinois, United States",2022-12-31,False,False,United States,None,NaN,NaN,Epsilon,"['sas', 'sas', 'sql', 'r', 'python', 'hadoop',...","{'analyst_tools': ['sas', 'word', 'excel', 'po...",1

## Dropping Data

### Notes

* Use `drop()` if you want to drop (delete) either a column or row in your database. 
* The syntax is:
    * Drop column: `df.drop('column_name, axis = 1)`
    * Drop row: `df.drop(index_name, axis = 0)`
* If you wanted to drop multiple rows you would have the syntax: 
    * Drop multiple columns: `df.drop(['column_name1', 'column_name2'], axis=1)`
    * Drop multiple rows: `df.drop([index_name1, index_name2], axis=0)`

### Examples

Let's drop the column `'salary_hour_avg'`, this will have an axis of 1 (since we're dropping a column).

In [8]:
df.drop('salary_hour_avg', axis = 1, inplace=True)

Inspecting the columns available now:

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 787686 entries, 287190 to 481817
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        787686 non-null  object
 1   job_title              787685 non-null  object
 2   job_location           786646 non-null  object
 3   job_via                787679 non-null  object
 4   job_schedule_type      774976 non-null  object
 5   job_work_from_home     787686 non-null  bool
 6   search_location        787686 non-null  object
 7   job_posted_date        787686 non-null  object
 8   job_no_degree_mention  787686 non-null  bool
 9   job_health_insurance   787686 non-null  bool
 10  job_country            787633 non-null  object
 11  salary_rate            33073 non-null   object
 12  salary_year_avg        22026 non-null   float64
 13  company_name           787668 non-null  object
 14  job_skills             670364 non-null  object
 15  job_type_skills        670364 non-null  object
 16  Is Data Analyst        787686 non-null  int64
dtypes: bool(3), float64(1), int64(1), object(12)
memory usage: 92.4+ MB

This column is now removed!

## Remove NA

### Notes

* To remove rows that contain empty cells use `dropna()`. 
* By default `dropna()` will return a *new* DataFrame, and won't change the original. 

### Example

Let's cleanup our `salary_year_avg` column by removing the `NaN` values in this column.

In [10]:
df.salary_year_avg.head()

287190   NaN
770443   NaN
770111   NaN
465217   NaN
449221   NaN
Name: salary_year_avg, dtype: float64

In [11]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [12]:
df.salary_year_avg.head()

776816     89204.0
290804    191000.0
464653    115000.0
141327    235847.0
416181    210000.0
Name: salary_year_avg, dtype: float64